parameters:
#    ayah.example.class: blackknight467\AYAHBundle\Example
    ayahPublisherKey: null
    ayahScoringKey: null

services:
    ayah.type:
        class: blackknight467\AYAHBundle\Type\AYAHType
        arguments: 
            - %ayahPublisherKey%
            - %ayahScoringKey%
        tags:
            - { name: form.type, alias: ayah }
