parameters:
#    ayah.example.class: blackknight467\AYAHBundle\Example

services:
#    ayah.example:
#        class: %ayah.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
